# 生产环境配置
spring:
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  application:
    name: binance-mining-pool-report-cron
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    idle-timeout: 600000
    maximum-pool-size: 10
    max-lifetime: 1800000
    minimum-idle: 5
  redis:
    # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    lettuce:
      shutdown-timeout: 60000
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 80
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 30000
        # 连接池中的最大空闲连接
        max-idle: 80
        # 连接池中的最小空闲连接
        min-idle: 50


#mybatis驼峰字段映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com:
      company: debug
  path: ./logs
pool:
  security:
    name:
      db1:
        # securityName
        - nkp-prodor-aws-pool-rds-key
        # securityRegion
        - us-west-2
      dbRead:
        # securityName
        - nkp-prodor-aws-pool-rds-key
        # securityRegion
        - us-west-2
      #redis配置
      redis:
        - nkp-prodor-aws-webapi-redis-key
        - us-west-2
      #accessToken
      accessToken:
        - nkp-prodor-aws-xxl-job-key
        - us-west-2
      #dbsecre配置
      dbSecretkey:
        - nkp-prodor-dbrecordcheck-key
        - us-west-2
      blockChairKey:
        - nkp-prodor-bitcoin-block-explorer-api-key
        - us-west-2
      tokenViewKey:
        - nkp-prodor-token-view-explorer-api-key
        - us-west-2
      #btc节点配置
      btcd:
        - nkp-prodor-aws-bitcoindrpc-key
        - us-west-2
      # zts 的密钥
      ztsApiKey:
        - tf-nkp-prodor-zts-api-key
        - us-west-2
      botSecret:
        - nkp-prodor-wea-notify-bot-key
        - us-west-2
  # 是否是线上的请求 0 是测试还
  onlineTest: 1
  domain: http://bp-prod-zts.awsnkp.internal
  bot:
    apiBase: https://openapi.difft.org
    botID: "+21006"